### ISSUE TITLE
Support for backticks with no parenthesis around them

### ISSUE THREAD

**Issue by roni-frantchi** [iservices/language-vscode-javascript-angular2#1]
Your extension is just what is was looking for.
Though I'm having an issue when i'm trying to use the backticks without parenthesis around them like you usually do in Angular2.

So while this **works**:

    @Component({
    template: (`
            <div #godiagram style="border: solid 1px black; width:400px; height:400px"></div>
        `)
    })

This one **does not work**:

    @Component({
    template: `
            <div #godiagram style="border: solid 1px black; width:400px; height:400px"></div>
        `
    })

Any chance of supporting the latter?..

Thanks

**Comment by natewallace** [comment]
I don't think this can be done easily(by me anyways) with the current syntax highlighter definitions.  Being able to identify when a string is used specifically as a value assignment for the template parameter in a ComponentMetadata class would be very difficult compared to the relatively simple solution of looking for a parens and back tick combo anywhere in the document.

I'm open to suggestions and/or pull requests though.

**Comment by roni-frantchi** [comment]
i'm thinking it might work if one of looking for open paren and backtick, one could look for:
```template: ` ``` as an opener and a single back tick to close it out.?
I'll create a pull request with the details.

**Comment by natewallace** [comment]
I'm closing this issue for now.  If a relatively easy implementation for this request comes to light then I will re-evaluate this issue.

**Comment by natewallace** [comment]
I've published version 0.0.4 of this extension which now includes support for highlighting text within back ticks that is assigned to the template property without using parens.
