### ISSUE TITLE
Add support for regular backticks

### ISSUE THREAD

**Issue by vectorhacker** [iservices/language-vscode-javascript-angular2#3]
While the parens backtick  is great, I would like for there to be support for simple backticks instead.

**Comment by natewallace** [comment]
This request is probably the same as issue: https://github.com/iservices/language-vscode-javascript-angular2/issues/1.  I'm assuming the desire is to have the highlighting work only when it's a template string in the template property of a component decorator.  This would require more complex changes to the language syntax than the simple matching on a '(`' character that is being done.  

I may try to tackle this in the future but I tend to struggle with parsing languages.

**Comment by natewallace** [comment]
I've published version 0.0.4 of this extension which now includes support for highlighting text within back ticks that is assigned to the template property without using parens.
