### ISSUE TITLE
two-way binding in Angular2 templates causes highlighting error

### ISSUE THREAD

**Issue by linusbrolin** [iservices/language-vscode-javascript-angular2#4]
When using two-way binding in Angular2 templates, this syntax highlighter gets buggy and potentially causes the syntax highlighting in the entire .ts file to go crazy:
![highlight_error](https://cloud.githubusercontent.com/assets/3481784/15649204/1e737e26-2670-11e6-82a8-50b50a68afe3.png)

Currently, the only way to somewhat work around this bug is to have a one-way binding line below the last two-way binding line:
![highlight_workaround](https://cloud.githubusercontent.com/assets/3481784/15649205/23e3f160-2670-11e6-8982-c30117884695.png)

But what is really needed is support for two-way binding in this plugin.

**Comment by natewallace** [comment]
Thanks for the bug report.  I've fixed an error in the regex used to identify attribute names so the two-way binding syntax should be handled correctly now.  This fix has been published with version 0.0.5.
